---
apiVersion: v1
kind: Namespace
metadata:
  name: bbcnews-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbc
  namespace: bbcnews-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbc
  template:
    metadata:
      labels:
        app: bbc
    spec:
      containers:
      - name: bbccontainer
        image: famidha/bbcsite:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: bbcsite
  namespace: bbcnews-ns
spec:
  selector:
    app: bbc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
